---
downloads: ~/.ansible-downloads/

homebrew_installed_packages:
  - ansible
  - autoconf
  - ctags
  - curl
  - git
  - go
  - htop
  - jq
  - mas
  - nvim
  - packer
  - pyenv
  - pyenv-virtualenv
  - terraform
  - tmux
  - tree
  - tig
  - wget
  - zlib
  - zsh
  - zsh-syntax-highlighting

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts
  - aws/tap

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - alfred
  - appcleaner
  - bartender
  - cleanshot
  - fork
  - firefox
  - font-jetbrains-mono
  - iina
  - insomnia
  - iterm2
  - jetbrains-toolbox
  - karabiner-elements
  - macfuse
  - obsidian
  - spotify
  - visual-studio-code
  - zoom

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps:
  - { id: 1333542190, name: "1Password" }
  - { name: "Amphetamine", id: 937984704 }
  - { id: 747648890, name: "Telegram" }
  - { name: "Magnet", id: 441258766 }
  - { name: "Reeder", id: 1529448980 }
  - { name: "The Unarchiver", id: 425424353 }
  - { name: "Things 3", id: 904280696 }
  - { name: "Day One", id: 1055511498 }
  - { name: "Fantastical", id: 975937182 }
  - { name: "GoodLinks", id: 1474335294 }
  - { name: "ForkLift", id: 412448059 }

mas_email: ""
mas_password: ""