---
- hosts: all

  vars_files:
    - vars/main.yml

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: homebrew
    - role: homebrew_cask
    - role: gantsign.oh-my-zsh
      users:
        - username: ceth
          oh_my_zsh:
            plugins:
              - command-not-found
              - git  # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
              - golang # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/golang
              - iterm2 # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/iterm2
              - macos # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/macos
              - tmux # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/tmux
              - vscode # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/vscode
              - zsh-interactive-cd # https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/zsh-interactive-cd
    - role: zsh
    - role: git
    - role: vscode
    - role: yandex
    - role: mac-osx
