---
- name: Avoid creating .DS_Store files on network or USB volumes
  shell: |
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

- name: Disable the warning before emptying the Trash
  shell: defaults write com.apple.finder WarnOnEmptyTrash -bool false

- name: Automatically hide and show the Dock
  shell: defaults write com.apple.dock autohide -bool true

- name: Don’t show recent applications in Dock
  shell: defaults write com.apple.dock show-recents -bool false

# iTerm
#

- name: Don’t display the annoying prompt when quitting iTerm
  shell: defaults write com.googlecode.iterm2 PromptOnQuit -bool false