---

homebrew_cask_appdir: /Applications
apps:
  - alfred
  - appcleaner
  - bartender
  - cleanshot
  - dash
  - fork
  - firefox
  - font-jetbrains-mono
  - iina
  - insomnia
  - iterm2
  - jetbrains-toolbox
  - karabiner-elements
  - macfuse
  - obsidian
  - spotify
  - tidal
  - transmission
  - zoom