---
# https://macos-defaults.com/#%F0%9F%99%8B-what-s-a-defaults-command

# Dock
#
- name: Put the Dock on the right of the screen
  shell: defaults write com.apple.dock orientation -string right

- name: Don’t show recent applications in Dock
  shell: defaults write com.apple.dock show-recents -bool false

# Finder
#

- name: "Finder: show all filename extensions"
  command: defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: "Finder: When performing a search, search the current folder by default"
  command: defaults write com.apple.finder FXDefaultSearchScope -string "SCcf" 

- name: Avoid creating .DS_Store files on network or USB volumes
  shell: |
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
    defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true

- name: Disable the warning before emptying the Trash
  shell: defaults write com.apple.finder WarnOnEmptyTrash -bool false

- name: "Don't Ask confirmation for change extension"
  command: defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# iTerm
#

- name: Don’t display the annoying prompt when quitting iTerm
  shell: defaults write com.googlecode.iterm2 PromptOnQuit -bool false